[workspace]
resolver = "3"
members = ["cenyslovensko_api", "cenyslovensko_rpc_server", "cenyslovensko_version_api", "cenyslovensko_web_client"]

[workspace.dependencies]
reqwest = "0.13.4"
tokio = "1.53.1"
serde = "1.0.229"
serde_json = "1.0.151"
derive_more = "2.1.1"
anyhow = "1.0.104"
miette = "7.6.0"
httpmock = "0.8.3"
