[package]
name = "cenyslovensko_vendor_api"
version = "0.1.14"
edition = "2024"
description = "Vendor API client for CenySlovensko."
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
derive_more = { workspace = true, features = ["display", "eq", "constructor", "error", "from"] }
miette = { workspace = true }
cenyslovensko_web_client = { path = "../cenyslovensko_web_client", version = "0.1.14" }

[dev-dependencies]
httpmock = { workspace = true }
criterion = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[[bench]]
name = "vendor_api_bench"
harness = false
