[package]
name = "cenyslovensko_rpc_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
cenyslovensko_web_client = { workspace = true }
cenyslovensko_version_api = { workspace = true }
