from __future__ import annotations

from typing import Protocol


class RpcTransport(Protocol):
    def start(self) -> None: ...

    def close(self) -> None: ...

    def write_line(self, line: str) -> None: ...

    def read_line(self) -> str: ...
